# Generated by Django 5.0.4 on 2024-04-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_name',
            new_name='img_url',
        ),
    ]
