# Generated by Django 5.0.4 on 2024-04-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_image_name_product_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
